name: IMU_Machine_Learning
channels:
  - plotly
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - _tflow_select=2.1.0=gpu
  - absl-py=0.8.1=py37_0
  - asn1crypto=1.2.0=py37_0
  - astor=0.8.0=py37_0
  - blas=1.0=mkl
  - ca-certificates=2020.10.14=0
  - certifi=2020.6.20=pyhd3eb1b0_3
  - cffi=1.13.2=py37h7a1dbc1_0
  - chardet=3.0.4=py37_1003
  - chart-studio=1.0.0=py_0
  - click=7.0=py37_0
  - cryptography=2.8=py37h7a1dbc1_0
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.5=cuda10.0_0
  - cycler=0.10.0=py37_0
  - dash=1.4.1=py_0
  - dash-core-components=1.3.1=py_0
  - dash-html-components=1.0.1=py_0
  - dash-renderer=1.1.2=py_0
  - dash-table=4.4.1=py_0
  - flask=1.1.1=py_0
  - flask-compress=1.4.0=py_0
  - freetype=2.9.1=ha9979f8_1
  - future=0.18.2=py37_0
  - gast=0.3.2=py_0
  - grpcio=1.16.1=py37h351948d_1
  - h5py=2.9.0=py37h5e291fa_0
  - hdf5=1.10.4=h7ebc959_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha66f8fd_1
  - idna=2.8=py37_0
  - intel-openmp=2019.4=245
  - itsdangerous=1.1.0=py37_0
  - jinja2=2.10.3=py_0
  - joblib=0.14.1=py_0
  - jpeg=9b=hb83a4c4_2
  - keras-applications=1.0.8=py_0
  - keras-base=2.3.1=py37_0
  - keras-gpu=2.3.1=0
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.1.0=py37ha925a31_0
  - libpng=1.6.37=h2a8f88b_0
  - libprotobuf=3.11.2=h7bd577a_0
  - libtiff=4.1.0=h56a325e_1
  - lz4-c=1.9.2=h62dcd97_1
  - markdown=3.1.1=py37_0
  - markupsafe=1.1.1=py37he774522_0
  - matplotlib=3.1.1=py37hc8f65d3_0
  - mkl=2019.4=245
  - mkl-service=2.3.0=py37hb782905_0
  - mkl_fft=1.0.15=py37h14836fe_0
  - mkl_random=1.1.0=py37h675688f_0
  - mock=3.0.5=py37_0
  - numpy=1.17.4=py37h4320e6b_0
  - numpy-base=1.17.4=py37hc3f5095_0
  - olefile=0.46=py_0
  - openssl=1.1.1h=he774522_0
  - pandas=0.25.3=py37ha925a31_0
  - pillow=7.0.0=py37hcc1f983_0
  - pip=19.3.1=py37_0
  - plotly=4.5.0=py_0
  - protobuf=3.11.2=py37h33f27b4_0
  - pycparser=2.19=py37_0
  - pyopenssl=19.1.0=py37_0
  - pyparsing=2.4.5=py_0
  - pyqt=5.9.2=py37h6538335_2
  - pyqtgraph=0.11.0=py_0
  - pyreadline=2.1=py37_1
  - pysocks=1.7.1=py37_0
  - python=3.7.5=h8c8aaf0_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2019.3=py_0
  - pyyaml=5.2=py37he774522_0
  - qt=5.9.7=vc14h73c81de_0
  - requests=2.22.0=py37_1
  - retrying=1.3.3=py37_2
  - scikit-learn=0.22.1=py37h6288b17_0
  - scipy=1.4.1=py37h9439919_0
  - setuptools=42.0.2=py37_0
  - sip=4.19.8=py37h6538335_0
  - six=1.13.0=py37_0
  - sqlite=3.30.1=he774522_0
  - tabulate=0.8.7=py37_0
  - tensorboard=1.14.0=py37he3c9ec2_0
  - tensorflow=1.14.0=gpu_py37h5512b17_0
  - tensorflow-base=1.14.0=gpu_py37h55fc52a_0
  - tensorflow-estimator=1.14.0=py_0
  - tensorflow-gpu=1.14.0=h0d30ee6_0
  - termcolor=1.1.0=py37_1
  - tk=8.6.10=hfa6e2cd_0
  - tornado=6.0.3=py37he774522_0
  - urllib3=1.25.7=py37_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_1
  - werkzeug=0.16.0=py_0
  - wheel=0.33.6=py37_0
  - win_inet_pton=1.1.0=py37_0
  - wincertstore=0.2=py37_0
  - wrapt=1.12.1=py37he774522_1
  - xz=5.2.5=h2fa13f4_0
  - yaml=0.1.7=hc54c509_2
  - zlib=1.2.11=h62dcd97_3
  - zstd=1.4.4=h9f78265_3
  - pip:
    - alabaster==0.7.12
    - babel==2.8.0
    - colorama==0.4.3
    - dill==0.3.1.1
    - docutils==0.16
    - emd-signal==0.2.7
    - imagesize==1.2.0
    - littleutils==0.2.2
    - multiprocess==0.70.9
    - numpydoc==0.9.2
    - ordered-set==3.1.1
    - outdated==0.2.0
    - packaging==20.1
    - pandas-flavor==0.2.0
    - pathos==0.2.5
    - patsy==0.5.1
    - pingouin==0.3.8
    - pox==0.2.7
    - ppft==1.6.6.1
    - pygame==1.9.6
    - pygments==2.5.2
    - pylatex==1.3.1
    - python-rapidjson==0.9.1
    - rapidjson==1.0.0
    - scikit-posthocs==0.6.2
    - seaborn==0.10.0
    - snowballstemmer==2.0.0
    - sphinx==2.4.1
    - sphinxcontrib-applehelp==1.0.1
    - sphinxcontrib-devhelp==1.0.1
    - sphinxcontrib-htmlhelp==1.0.2
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.2
    - sphinxcontrib-serializinghtml==1.1.3
    - statsmodels==0.11.0
    - xarray==0.16.0
prefix: C:\Users\hisha\Anaconda3\envs\IMU_class_2020
